# Generated by Django 5.2.1 on 2025-06-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-date"]},
        ),
    ]
