version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/python:3.10  # image CircleCI officielle avec python & pip
    steps:
      - checkout
      - setup_remote_docker  # ⬅️ version supprimée ici
      - run:
          name: Build docker images
          command: docker-compose build
      - run:
          name: Start containers (détaché)
          command: docker-compose up -d
      - run:
          name: Run Django tests
          command: docker-compose run web python manage.py test
      - run:
          name: Tear down containers
          command: docker-compose down

workflows:
  version: 2
  test_workflow:
    jobs:
      - run_tests

