version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/python:3.10  # image CircleCI officielle avec python & pip
    steps:
      - checkout
      - setup_remote_docker  # ⬅️ version supprimée ici
      - run:
          name: Build docker images
          command: docker-compose -f docker-compose.yml build
      - run:
          name: Start containers (détaché)
          command: docker-compose -f docker-compose.yml up
      - run:
          name: Debug project files
          command: docker-compose -f docker-compose.yml run web ls /app

      - run:
          name: Run Django tests
          command: docker-compose -f docker-compose.yml run web python manage.py test
      - run:
          name: Tear down containers
          command: docker-compose down

workflows:
  version: 2
  test_workflow:
    jobs:
      - run_tests

