version: 2.1

jobs:
  run_tests:
    docker:
      - image: python:3.10-slim
    steps:
      - checkout
      - run:
          name: Build docker
          command: docker-compose build
      - run:
          name: Run docker
          command: docker-compose up
      - run:
          name: Run Django tests
          command: docker-compose run web python manage.py test

workflows:
  version: 2
  test_workflow:
    jobs:
      - run_tests
