version: 2.1

jobs:
  run_tests:
    docker:
      - image: python:3.10-slim
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Django tests
          command: python manage.py test

workflows:
  version: 2
  test_workflow:
    jobs:
      - run_tests
